"""
Integration tests for the Julia/ModelingToolkit builder.

Two tiers:

Tier 1 — Translation tests (no Julia required, always run in CI)
    Parametrised over every .mdl file in tests/test-models/tests/.
    Checks that translate_to_julia() produces a .jl file with the
    expected structural markers.  Models that emit UserWarnings for
    unsupported constructs are accepted; the test only fails if an
    unexpected exception is raised.

    A separate, stricter sub-set checks the 53 models that are fully
    supported (no warnings at all) to guard against regressions.

Tier 2 — Numerical validation (requires Julia + ModelingToolkit.jl)
    Marked with @pytest.mark.julia — skipped automatically when the
    julia binary is not found.
    For each model that has an output.csv reference file the test:
      1. translates the .mdl to .jl
      2. generates a small Julia driver script that runs the model and
         writes results to CSV via stdout
      3. executes the driver with subprocess and parses the CSV
      4. compares every column against the reference within tolerance

    Variable names in output.csv are mapped to Julia identifiers via the
    same JuliaNamespaceManager used by the builder, so the comparison is
    exact (no manual name mapping required).

To run only the numerical tier:
    pytest tests/pytest_builders/pytest_julia_integration.py -m julia -v
"""
from __future__ import annotations

import csv
import io
import re
import shutil
import subprocess
import tempfile
import warnings
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import pytest

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

TEST_MODELS_DIR = Path("tests/test-models/tests")
SAMPLES_DIR = Path("tests/test-models/samples")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _all_mdl_files() -> List[Tuple[str, Path]]:
    """Return (folder_name, model_path) for every model in tests/test-models/tests/.

    Handles both lowercase .mdl and uppercase .MDL extensions (Linux is case-sensitive).
    XMILE-only folders (no .mdl/.MDL file) are included via their .xmile file.
    """
    results = []
    mdl_folders: set = set()
    for mdl in sorted(TEST_MODELS_DIR.glob("*/*.mdl")):
        results.append((mdl.parent.name, mdl))
        mdl_folders.add(mdl.parent.name)
    # Uppercase .MDL (e.g. case_sensitive_extension)
    for mdl in sorted(TEST_MODELS_DIR.glob("*/*.MDL")):
        folder = mdl.parent.name
        if folder not in mdl_folders:
            results.append((folder, mdl))
            mdl_folders.add(folder)
    for xmile in sorted(TEST_MODELS_DIR.glob("*/*.xmile")):
        folder = xmile.parent.name
        if folder not in mdl_folders:
            results.append((folder, xmile))
    return sorted(results)


def _output_csv_path(folder: str) -> Path | None:
    """Return the output.csv path for *folder*, or None if it does not exist."""
    p = TEST_MODELS_DIR / folder / "output.csv"
    return p if p.exists() else None


def _read_csv(path: Path) -> Dict[str, List[float]]:
    """Read a CSV into {column_name: [float, ...]}."""
    result: Dict[str, List[float]] = {}
    with path.open(newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            for k, v in row.items():
                result.setdefault(k, []).append(float(v))
    return result


def _isclose(a: float, b: float, rtol: float = 1e-3, atol: float = 1e-4) -> bool:
    """Return True if a ≈ b within the tolerances used by the test-models suite.

    Passes when EITHER:
    * both values are near zero (< atol), OR
    * relative difference ≤ rtol, OR
    * absolute difference ≤ atol  (covers small values where rtol is too strict,
      e.g. interpolation differences on values close to but above atol)
    """
    if a == b:
        return True
    near_zero = abs(a) < atol and abs(b) < atol
    return (
        near_zero
        or abs(a - b) <= rtol * max(abs(a), abs(b))
        or abs(a - b) <= atol
    )


# ---------------------------------------------------------------------------
# Tier 1 helpers
# ---------------------------------------------------------------------------

#: Models that translate cleanly with zero UserWarnings.
#: Generated by running translate_to_julia over the full test-models suite
#: and collecting those that produce no warnings.
CLEAN_MODELS: List[str] = [
    "abs",
    "active_initial",
    "active_initial_circular",
    "allocate_available",
    "allocate_by_priority",
    "arguments",
    "arithmetics",
    "arithmetics_exp",
    "array_with_line_break",
    "builtin_max",
    "builtin_min",
    "case_sensitive_extension",
    "chained_initialization",
    "comparisons",
    "conditional_subscripts",
    "constant_expressions",
    "control_vars",
    "data_from_other_model",
    "delay_numeric_error",
    "delay_parentheses",
    "delay_xmile",
    "dynamic_final_time",
    "elm_count",
    "euler_step_vs_saveper",
    "eval_order",
    "except",
    "except_multiple",
    "except_subranges",
    "exp",
    "exponentiation",
    "forecast",
    "fully_invalid_names",
    "function_capitalization",
    "game",
    "get_constants",
    "get_constants_incomplete_subscript",
    "get_constants_subranges",
    "get_data",
    "get_data_args_3d_xls",
    "get_lookups_data_3d_xls",
    "get_lookups_subscripted_args",
    "get_lookups_subset",
    "get_mixed_definitions",
    "get_subscript_3d_arrays_xls",
    "min_max_1arg",
    "get_time_value",
    "get_values_order",
    "get_with_missing_values_xlsx",
    "get_xls_cellrange",
    "if_stmt",
    "initial_function",
    "input_functions",
    "invert_matrix",
    "limits",
    "line_breaks",
    "line_continuation",
    "ln",
    "log",
    "logicals",
    "lookups",
    "lookups_funcnames",
    "lookups_inline",
    "lookups_inline_bounded",
    "lookups_inline_spaces",
    "lookups_with_expr",
    "lookups_without_range",
    "macro_cross_reference",
    "macro_expression",
    "macro_multi_expression",
    "macro_multi_macros",
    "macro_trailing_definition",
    "model_doc",
    "multiple_lines_def",
    "na",
    "nested_functions",
    "non_negative_all",
    "non_negative_flows",
    "non_negative_stocks",
    "number_handling",
    "parentheses",
    "partial_range_definitions",
    "pi",
    "power",
    "reference_capitalization",
    "repeated_subscript",
    "rounding",
    "sample_if_true",
    "smaller_range",
    "smooth_and_stock",
    "special_characters",
    "special_characters_xmile",
    "sqrt",
    "subrange_merge",
    "subscript_1d_arrays",
    "subscript_2d_arrays",
    "subscript_3d_arrays",
    "subscript_3d_arrays_lengthwise",
    "subscript_3d_arrays_widthwise",
    "subscript_aggregation",
    "subscript_constant_call",
    "subscript_copy",
    "subscript_definition",
    "subscript_docs",
    "subscript_element_name",
    "subscript_individually_defined_1_of_2d_arrays",
    "subscript_individually_defined_1_of_2d_arrays_from_floats",
    "subscript_individually_defined_1d_arrays",
    "subscript_individually_defined_stocks",
    "subscript_logicals",
    "subscript_mapping_simple",
    "subscript_mapping_vensim",
    "subscript_mixed_assembly",
    "subscript_multiples",
    "subscript_numeric_range",
    "subscript_selection",
    "subscript_subranges",
    "subscript_subranges_equal",
    "subscript_switching",
    "subscript_transposition",
    "subscript_updimensioning",
    "subscripted_delays",
    "subscripted_flows",
    "subscripted_if_then_else",
    "subscripted_logicals",
    "subscripted_lookups",
    "subscripted_ramp_step",
    "subscripted_round",
    "subscripted_trend",
    "subscripted_trig",
    "subscripted_xidz",
    "subset_duplicated_coord",
    "tabbed_arrays",
    "time",
    "trend",
    "trig",
    "unchangeable_constant",
    "unicode_characters",
    "variable_ranges",
    "vector_order",
    "vector_select",
    "with_lookup",
    "xidz_zidz",
    "zeroled_decimals",
]

#: Models that have an output.csv and are fully supported (clean translation).
#: Used for numerical validation tests.
NUMERICAL_MODELS: List[str] = [
    "abs",
    "builtin_max",
    "builtin_min",
    "case_sensitive_extension",
    "comparisons",
    "delay_fixed",
    "delays",
    "eval_order",
    "exp",
    "if_stmt",
    "initial_function",
    "input_functions",
    "logicals",
    "lookups_with_expr",
    "number_handling",
    "odd_number_quotes",
    "smooth",
    "sqrt",
    "subscript_1d_arrays",
    "subscript_individually_defined_1d_arrays",
    "subscripted_delays",
    "trend",
    "trig",
]

# Cache the result so the subprocess is only run once per session.
_julia_mtk_available_cache: bool | None = None


def _julia_mtk_available() -> bool:
    """Return True iff Julia is on PATH and OrdinaryDiffEq is loadable."""
    global _julia_mtk_available_cache
    if _julia_mtk_available_cache is not None:
        return _julia_mtk_available_cache
    if shutil.which("julia") is None:
        _julia_mtk_available_cache = False
        return False
    try:
        result = subprocess.run(
            ["julia", "--startup-file=no", "-e", "using OrdinaryDiffEq"],
            capture_output=True,
            timeout=60,
        )
        _julia_mtk_available_cache = result.returncode == 0
    except (subprocess.TimeoutExpired, OSError):
        _julia_mtk_available_cache = False
    return _julia_mtk_available_cache


# ---------------------------------------------------------------------------
# Tier 1 — Translation tests
# ---------------------------------------------------------------------------

class TestTranslationAllModels:
    """Translate every .mdl in test-models; assert the .jl file is created."""

    @pytest.mark.parametrize(
        "folder,mdl_path",
        _all_mdl_files(),
        ids=[f for f, _ in _all_mdl_files()],
    )
    @pytest.mark.filterwarnings("ignore::UserWarning")
    def test_produces_jl_file(self, folder, mdl_path, tmp_path):
        """translate_to_julia() must not raise and must create a .jl file."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        assert jl_path.exists(), f"{folder}: .jl file was not created"
        assert jl_path.suffix == ".jl"

    @pytest.mark.parametrize(
        "folder,mdl_path",
        _all_mdl_files(),
        ids=[f for f, _ in _all_mdl_files()],
    )
    @pytest.mark.filterwarnings("ignore::UserWarning")
    def test_jl_contains_required_sections(self, folder, mdl_path, tmp_path):
        """Generated .jl must contain the structural markers of a valid MTK model."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        content = jl_path.read_text(encoding="utf-8")

        assert "using OrdinaryDiffEq" in content, f"{folder}: missing 'using OrdinaryDiffEq'"
        assert "function rhs!" in content, f"{folder}: missing 'function rhs!'"
        assert "run_model" in content, f"{folder}: missing 'run_model'"
        assert "function observe" in content, f"{folder}: missing 'function observe'"


class TestTranslationCleanModels:
    """Models in CLEAN_MODELS must translate with zero UserWarnings."""

    @pytest.mark.parametrize(
        "folder,mdl_path",
        [(f, p) for f, p in _all_mdl_files() if f in CLEAN_MODELS],
        ids=[f for f, _ in _all_mdl_files() if f in CLEAN_MODELS],
    )
    def test_no_warnings(self, folder, mdl_path, tmp_path):
        """Clean models must not emit any UserWarning during translation."""
        import shutil as _shutil
        model_dir = tmp_path / folder
        _shutil.copytree(mdl_path.parent, model_dir)
        dst = model_dir / mdl_path.name

        from pysd import translate_to_julia

        # With filterwarnings=error in pytest.ini, any UserWarning becomes an
        # error, so we just call translate_to_julia normally.
        jl_path = translate_to_julia(dst)
        assert jl_path.exists()

    @pytest.mark.parametrize(
        "folder,mdl_path",
        [(f, p) for f, p in _all_mdl_files() if f in CLEAN_MODELS],
        ids=[f for f, _ in _all_mdl_files() if f in CLEAN_MODELS],
    )
    def test_stocks_declared(self, folder, mdl_path, tmp_path):
        """Models with stocks must declare @variables ... (t) in the output."""
        import shutil as _shutil
        model_dir = tmp_path / folder
        _shutil.copytree(mdl_path.parent, model_dir)
        dst = model_dir / mdl_path.name

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        content = jl_path.read_text(encoding="utf-8")
        # Every model has at minimum the ODE boilerplate
        assert "function rhs!" in content

    @pytest.mark.parametrize(
        "folder,mdl_path",
        [(f, p) for f, p in _all_mdl_files() if f in CLEAN_MODELS],
        ids=[f for f, _ in _all_mdl_files() if f in CLEAN_MODELS],
    )
    def test_control_vars_emitted(self, folder, mdl_path, tmp_path):
        """Control variables (initial/final time, dt) must appear in output."""
        import shutil as _shutil
        model_dir = tmp_path / folder
        _shutil.copytree(mdl_path.parent, model_dir)
        dst = model_dir / mdl_path.name

        from pysd import translate_to_julia

        jl_path = translate_to_julia(dst)
        content = jl_path.read_text(encoding="utf-8")
        assert "initial_time" in content
        assert "final_time" in content
        assert "time_step" in content


# ---------------------------------------------------------------------------
# Tier 1 — Feature-specific translation tests
# ---------------------------------------------------------------------------

class TestTranslationFeatures:
    """Spot-check that specific SD constructs produce the expected Julia output."""

    def _translate(self, folder: str, tmp_path: Path) -> str:
        import shutil as _shutil
        mdl = next((TEST_MODELS_DIR / folder).glob("*.mdl"))
        dst = tmp_path / mdl.name
        _shutil.copy(mdl, dst)
        from pysd import translate_to_julia
        return translate_to_julia(dst).read_text(encoding="utf-8")

    def test_integ_emits_ode(self, tmp_path):
        content = self._translate("abs", tmp_path)
        assert "du[" in content, "INTEG must produce du[i] = ... ODE derivative"

    def test_lookup_emits_interpolation(self, tmp_path):
        content = self._translate("lookups_inline", tmp_path)
        assert "LinearInterpolation" in content
        assert "DataInterpolations" in content

    def test_smooth_emits_auxiliary_stocks(self, tmp_path):
        content = self._translate("smooth_and_stock", tmp_path)
        assert "_lv" in content, "SMOOTH must introduce auxiliary level stocks"

    def test_xidz_emits_helper(self, tmp_path):
        content = self._translate("xidz_zidz", tmp_path)
        assert "_xidz" in content or "_zidz" in content

    def test_input_functions_emit_helpers(self, tmp_path):
        content = self._translate("input_functions", tmp_path)
        assert "_pulse(" in content or "_ramp(" in content or "_step(" in content

    def test_if_then_else_maps_to_ifelse(self, tmp_path):
        content = self._translate("if_stmt", tmp_path)
        assert "ifelse(" in content

    def test_logicals_map_to_julia_operators(self, tmp_path):
        content = self._translate("logicals", tmp_path)
        # AND/OR/NOT use helper functions for MTK symbolic compatibility
        assert "_logical_and" in content or "_logical_or" in content or "_logical_not" in content

    def test_lookup_with_expr_emits_interpolation(self, tmp_path):
        content = self._translate("lookups_with_expr", tmp_path)
        assert "LinearInterpolation" in content

    def test_game_passthrough(self, tmp_path):
        """GAME should not break translation."""
        content = self._translate("game", tmp_path)
        assert "function rhs!" in content

    @pytest.mark.filterwarnings("ignore::UserWarning")
    def test_delay_emits_pipeline_levels(self, tmp_path):
        """DELAY1 / DELAY3 expand into auxiliary _dl level stocks."""
        content = self._translate("delays", tmp_path)
        assert "_dl" in content, "DELAY must introduce pipeline level variables"
        assert "du[" in content, "each DELAY level must have its own ODE derivative"


# ---------------------------------------------------------------------------
# Tier 1 — Modular (split-views) translation
# ---------------------------------------------------------------------------

class TestModularTranslation:
    """split_views=True is MTK-backend only; creates main .jl plus per-view module files."""

    def test_split_model_creates_modules_dir(self, tmp_path):
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            jl_path = translate_to_julia(dst, split_views=True, backend="mtk")

        modules_dir = tmp_path / f"modules_{dst.stem}"
        assert jl_path.exists()
        assert modules_dir.exists(), "modules directory must be created for split models"

    def test_split_model_module_files_exist(self, tmp_path):
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            translate_to_julia(dst, split_views=True, backend="mtk")

        modules_dir = tmp_path / f"modules_{dst.stem}"
        jl_files = list(modules_dir.rglob("*.jl"))
        assert len(jl_files) > 0, "at least one module .jl file must be created"

    def test_split_model_main_includes_modules(self, tmp_path):
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            jl_path = translate_to_julia(dst, split_views=True, backend="mtk")

        content = jl_path.read_text(encoding="utf-8")
        assert "include(" in content

    def test_split_model_all_declarations_in_main(self, tmp_path):
        """Variable declarations must be in the main file so all modules can reference them."""
        import shutil as _shutil
        src = Path("tests/more-tests/split_model/test_split_model.mdl")
        if not src.exists():
            pytest.skip("split_model fixture not available")

        dst = tmp_path / src.name
        _shutil.copy(src, dst)

        from pysd import translate_to_julia

        with warnings.catch_warnings():
            warnings.simplefilter("ignore", UserWarning)
            jl_path = translate_to_julia(dst, split_views=True, backend="mtk")

        content = jl_path.read_text(encoding="utf-8")
        assert "run_model" in content
        assert "include(" in content


# ---------------------------------------------------------------------------
# Tier 2 — Numerical validation (requires Julia)
# ---------------------------------------------------------------------------

def _julia_runner_script(model_jl: Path, col_names: List[str],
                         julia_ids: List[str], t_ref: List[float]) -> str:
    """
    Generate a self-contained Julia script that:
      1. includes the generated model file
      2. runs the model with the Euler solver
      3. prints a CSV with Time + one column per variable
         (using MTK symbolic indexing — works for both stocks and observed vars)
    """
    t_array = "[" + ", ".join(str(t) for t in t_ref) + "]"

    col_header = ", ".join(f'"{c}"' for c in col_names)
    julia_id_strs = ", ".join(f'"{j}"' for j in julia_ids)

    return f"""\
include("{model_jl.as_posix()}")

using Printf

sol = run_model(; solver=Euler())

col_display = [{col_header}]
julia_ids   = [{julia_id_strs}]
t_ref       = {t_array}

# Build time-series for each variable.
# Handles: ODE states, observed (algebraic) auxiliaries, and global @parameters
# (which live at module scope, not in sys, so sys.name would throw).
function _get_series(sol, id_str)
    sym = nothing
    try; sym = getproperty(sys, Symbol(id_str)); catch; end

    if sym !== nothing
        try; return Float64.(sol[sym, :]); catch; end
        try; return fill(Float64(sol.prob.ps[sym]), length(sol.t)); catch; end
    end
    # Bare global @parameters (not included in ODESystem equations).
    # Use ModelingToolkit.getdefault() to extract the concrete default value.
    try
        p = Base.eval(Main, Symbol(id_str))
        val = Float64(ModelingToolkit.getdefault(p))
        return fill(val, length(sol.t))
    catch
    end
    return fill(NaN, length(sol.t))
end

col_series = [_get_series(sol, id) for id in julia_ids]

# CSV output: header uses original column names; rows sampled at t_ref
print("Time")
for n in col_display; print(",", n); end
println()

for t in t_ref
    @printf("%g", t)
    idx = argmin(abs.(sol.t .- t))
    for vals in col_series; @printf(",%g", vals[idx]); end
    println()
end
"""


def _run_julia(script_path: Path, timeout: int = 120) -> str:
    """Run a Julia script and return its stdout, raising on non-zero exit."""
    result = subprocess.run(
        ["julia", "--startup-file=no", str(script_path)],
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    if result.returncode != 0:
        raise RuntimeError(
            f"Julia script failed (exit {result.returncode}):\n"
            f"STDOUT: {result.stdout[:500]}\n"
            f"STDERR: {result.stderr[:500]}"
        )
    return result.stdout


def _parse_csv_from_string(text: str) -> Dict[str, List[float]]:
    result: Dict[str, List[float]] = {}
    reader = csv.DictReader(io.StringIO(text.strip()))
    for row in reader:
        for k, v in row.items():
            try:
                result.setdefault(k, []).append(float(v))
            except ValueError:
                result.setdefault(k, []).append(float("nan"))
    return result


# ---------------------------------------------------------------------------
# Batch Julia runner — runs all models in ONE Julia process
# ---------------------------------------------------------------------------

_JL_PACKAGES = (
    "OrdinaryDiffEq, OrdinaryDiffEqLowOrderRK, "
    "DataInterpolations, NCDatasets, Printf"
)

_BATCH_GET_SERIES = """\
function _batch_get_series(sol, mod, id_str)
    # Parse optional array subscript: "stock_a[2]" → base="stock_a", elem_idx=2
    m = match(r"^(\\w+)\\[(\\d+)\\]$", id_str)
    base_id  = m === nothing ? id_str : m.captures[1]
    elem_idx = m === nothing ? nothing : parse(Int, m.captures[2])
    _extract(val) = elem_idx === nothing ? Float64(val) : Float64(val[elem_idx])

    # ODE backend: use observe(u, t) to reconstruct all variables
    if isdefined(mod, :observe)
        try
            return [let obs = mod.observe(sol.u[i], sol.t[i])
                        haskey(obs, base_id) ? _extract(obs[base_id]) : NaN
                    end for i in eachindex(sol.t)]
        catch
        end
    end
    # MTK backend: use sys for symbolic access
    sym = nothing
    try; sym = getproperty(mod.sys, Symbol(base_id)); catch; end
    if sym !== nothing
        try; return Float64.(sol[sym, :]); catch; end
        try; return fill(Float64(sol.prob.ps[sym]), length(sol.t)); catch; end
    end
    return fill(NaN, length(sol.t))
end
"""


def _julia_batch_script(
    models: "List[Tuple[str, Path, List[str], List[str], List[float]]]",
) -> str:
    """
    Build a Julia script that runs *all* models in one process.

    Each model is isolated in its own ``module`` block so that symbol names
    (sys, u0, eqs, run_model …) cannot clash between models.  Packages are
    loaded once at the top level; the per-module ``using`` statements just
    re-import already-loaded names into the module's namespace (microseconds).

    Output format
    -------------
    For each model the script prints::

        ===MODEL=<name>===
        Time,ColA,ColB,...
        0.0,v0a,v0b,...
        ...
        ===ENDMODEL===
    """
    lines = [f"using {_JL_PACKAGES}", "", _BATCH_GET_SERIES]

    for name, jl_path, col_names, julia_ids, t_ref in models:
        safe = re.sub(r"[^a-zA-Z0-9_]", "_", name)
        t_arr = "[" + ", ".join(str(t) for t in t_ref) + "]"
        col_hdr = ", ".join(f'"{c}"' for c in col_names)
        id_strs = ", ".join(f'"{j}"' for j in julia_ids)

        lines += [
            f"# --- {name} ---",
            f"module _M_{safe}",
            f"    using {_JL_PACKAGES}",
            f'    include("{jl_path.as_posix()}")',
            f"end",
            f"let",
            f"    local sol = _M_{safe}.run_model(; solver=Euler())",
            f"    local julia_ids = [{id_strs}]",
            f"    local t_ref = {t_arr}",
            f'    println("===MODEL={name}===")',
            f'    print("Time")',
            f"    for c in [{col_hdr}]; print(\",\", c); end",
            f"    println()",
            f"    for t in t_ref",
            f"        @printf(\"%g\", t)",
            f"        local idx = argmin(abs.(sol.t .- t))",
            f"        for id in julia_ids",
            f"            local vals = _batch_get_series(sol, _M_{safe}, id)",
            f"            @printf(\",%g\", vals[idx])",
            f"        end",
            f"        println()",
            f"    end",
            f'    println("===ENDMODEL===")',
            f"end",
            "",
        ]

    return "\n".join(lines)


def _parse_batch_output(stdout: str) -> "Dict[str, Dict[str, List[float]]]":
    """Split batch output by model markers and parse each CSV block."""
    results: Dict[str, Dict[str, List[float]]] = {}
    current: Optional[str] = None
    buf: List[str] = []
    for line in stdout.splitlines():
        if line.startswith("===MODEL=") and line.endswith("==="):
            current = line[9:-3]
            buf = []
        elif line == "===ENDMODEL===":
            if current is not None and buf:
                results[current] = _parse_csv_from_string("\n".join(buf))
            current = None
            buf = []
        elif current is not None:
            buf.append(line)
    return results


def _find_model_file(folder: Path) -> Optional[Path]:
    """Return the first supported model file in *folder* (MDL or XMILE, any case)."""
    for pattern in ("*.mdl", "*.MDL", "*.xmile", "*.stmx"):
        m = next(folder.glob(pattern), None)
        if m is not None:
            return m
    return None


def _build_id_map(mdl: Path, ref_cols: List[str]) -> Dict[str, str]:
    """Map ref CSV column names → Julia identifiers.

    Handles plain columns ('Stock A' → 'stock_a') and subscripted columns
    ('Stock A[Entry 1]' → 'stock_a[1]') using the model's subscript ranges.
    """
    from pysd.builders.julia.namespace import JuliaNamespaceManager

    suffix = mdl.suffix.lower()
    if suffix in (".xmile", ".stmx", ".xml"):
        from pysd.translators.xmile.xmile_file import XmileFile
        vf = XmileFile(mdl)
    else:
        from pysd.translators.vensim.vensim_file import VensimFile
        vf = VensimFile(mdl)

    vf.parse()
    am = vf.get_abstract_model()
    ns = JuliaNamespaceManager()
    for section in am.sections:
        for elem in section.elements:
            ns.add_to_namespace(elem.name)

    # Flat label→1-based-index from all subscript ranges.
    # Later ranges overwrite earlier ones for the same label — fine in practice
    # because element labels are unique across dimensions within a model.
    label_to_idx: Dict[str, int] = {}
    for section in am.sections:
        for sr in section.subscripts:
            for i, label in enumerate(sr.subscripts):
                label_to_idx[label.lower().strip()] = i + 1

    result: Dict[str, str] = {}
    for col in ref_cols:
        if col.lower() == "time":
            continue
        if "[" in col:
            base, rest = col.split("[", 1)
            label = rest.rstrip("]").strip()
            julia_id = ns.get(base.strip())
            if julia_id is not None:
                idx = label_to_idx.get(label.lower().strip())
                if idx is not None:
                    result[col] = f"{julia_id}[{idx}]"
        else:
            julia_id = ns.get(col)
            if julia_id is not None:
                result[col] = julia_id
    return result


# ---------------------------------------------------------------------------
# Session fixtures — translate + run all models in one Julia call
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def julia_numerical_results(tmp_path_factory):
    """Translate & run all TestNumericalValidation models in a single Julia process."""
    if not _julia_mtk_available():
        pytest.skip("Julia not available")

    import shutil as _sh
    import warnings
    from pysd import translate_to_julia

    tmp = tmp_path_factory.mktemp("julia_numerical")
    folders = [
        "abs", "builtin_max", "builtin_min", "case_sensitive_extension",
        "comparisons", "delay_fixed", "delays", "eval_order", "exp",
        "if_stmt", "initial_function", "input_functions", "logicals",
        "lookups_with_expr", "number_handling", "odd_number_quotes",
        "smooth", "sqrt", "subscript_1d_arrays",
        "subscript_individually_defined_1d_arrays", "subscripted_delays",
        "trend", "trig",
    ]

    models = []
    for folder in folders:
        mdl = _find_model_file(TEST_MODELS_DIR / folder)
        if mdl is None or not (TEST_MODELS_DIR / folder / "output.csv").exists():
            continue
        dst = tmp / folder / mdl.name
        dst.parent.mkdir(exist_ok=True)
        _sh.copy(mdl, dst)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            jl_path = translate_to_julia(dst)
            ref = _read_csv(TEST_MODELS_DIR / folder / "output.csv")
            id_map = _build_id_map(mdl, list(ref.keys()))
        if not id_map:
            continue
        col_names = list(id_map.keys())
        julia_ids = [id_map[c] for c in col_names]
        models.append((folder, jl_path, col_names, julia_ids, ref["Time"]))

    if not models:
        pytest.skip("No numerical test models found")

    script_path = tmp / "_batch_numerical.jl"
    script_path.write_text(_julia_batch_script(models))
    stdout = _run_julia(script_path, timeout=1800)
    return _parse_batch_output(stdout)


@pytest.fixture(scope="session")
def julia_constructs_results(tmp_path_factory):
    """Translate & run all TestNewConstructsNumerical models in one Julia process."""
    if not _julia_mtk_available():
        pytest.skip("Julia not available")

    import shutil as _sh
    import warnings
    from pysd import translate_to_julia
    from pysd.builders.julia.namespace import JuliaNamespaceManager
    from pysd.translators.vensim.vensim_file import VensimFile

    tmp = tmp_path_factory.mktemp("julia_constructs")
    t_ref = list(range(0, 11))

    specs = [
        ("delay_fixed",  MORE_TESTS_DIR / "julia_delay_fixed"    / "test_julia_delay_fixed.mdl",    ["Output"]),
        ("trend",        MORE_TESTS_DIR / "julia_trend"           / "test_julia_trend.mdl",          ["Trend Output"]),
        ("forecast",     MORE_TESTS_DIR / "julia_forecast"        / "test_julia_forecast.mdl",       ["Forecast Output", "Input"]),
        ("sample_if_true", MORE_TESTS_DIR / "julia_sample_if_true" / "test_julia_sample_if_true.mdl", ["Sampled Value"]),
    ]

    models = []
    for name, mdl, var_names in specs:
        if not mdl.exists():
            continue
        dst = tmp / mdl.name
        _sh.copy(mdl, dst)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            jl_path = translate_to_julia(dst)
        vf = VensimFile(dst)
        vf.parse()
        am = vf.get_abstract_model()
        ns = JuliaNamespaceManager()
        for section in am.sections:
            for elem in section.elements:
                ns.add_to_namespace(elem.name)
        julia_ids = [ns.get(v) or v for v in var_names]
        models.append((name, jl_path, var_names, julia_ids, t_ref))

    if not models:
        pytest.skip("No construct test models found")

    script_path = tmp / "_batch_constructs.jl"
    script_path.write_text(_julia_batch_script(models))
    stdout = _run_julia(script_path, timeout=1800)
    return _parse_batch_output(stdout)


# ---------------------------------------------------------------------------
# Tier 2 — Numerical validation
# ---------------------------------------------------------------------------

@pytest.mark.julia
@pytest.mark.skipif(
    not _julia_mtk_available(),
    reason="julia binary not found or ModelingToolkit.jl / OrdinaryDiffEq.jl not installed",
)
class TestNumericalValidation:
    """
    Numerical validation against output.csv reference values.

    All models are run in a single Julia process (session fixture) so
    package JIT cost is paid once, not once per test.
    """

    def _get_julia_ids(self, folder: str, ref_cols: List[str]) -> Dict[str, str]:
        """
        Map output.csv column names → Julia identifiers via JuliaNamespaceManager.
        Build the namespace by running the parser on the model (without writing
        the .jl file) so we get the exact same namespace the builder uses.
        """
        from pysd.builders.julia.namespace import JuliaNamespaceManager
        from pysd.translators.vensim.vensim_file import VensimFile

        mdl = next((TEST_MODELS_DIR / folder).glob("*.mdl"))
        vf = VensimFile(mdl)
        vf.parse()
        am = vf.get_abstract_model()

        ns = JuliaNamespaceManager()
        for section in am.sections:
            for elem in section.elements:
                ns.add_to_namespace(elem.name)

        mapping = {}
        for col in ref_cols:
            if col.lower() == "time":
                continue
            julia_id = ns.get(col)
            if julia_id:
                mapping[col] = julia_id
        return mapping

    def _compare(self, folder: str, ref: Dict, sim: Dict,
                 rtol: float = 1e-3, atol: float = 1e-4,
                 extra_ignore: set = None) -> None:
        """Assert all shared columns match within tolerance."""
        IGNORABLE = {
            "saveper", "initial_time", "final_time", "time_step", "time",
            # Vensim CSV headers use spaces; normalise both forms
            "initial time", "final time", "time step",
        }
        if extra_ignore:
            IGNORABLE = IGNORABLE | {c.lower() for c in extra_ignore}
        failures = []

        for col, ref_vals in ref.items():
            if col.lower() in IGNORABLE:
                continue
            if col not in sim:
                continue  # variable not accessible — skip rather than fail

            sim_vals = sim[col]
            if len(ref_vals) != len(sim_vals):
                failures.append(
                    f"{col}: length mismatch ({len(ref_vals)} vs {len(sim_vals)})"
                )
                continue

            for i, (r, s) in enumerate(zip(ref_vals, sim_vals)):
                if not _isclose(r, s, rtol=rtol, atol=atol):
                    failures.append(
                        f"{col}[{i}]: expected {r}, got {s} (t={ref['Time'][i]})"
                    )

        assert not failures, (
            f"{folder}: {len(failures)} comparison failure(s):\n"
            + "\n".join(failures[:10])
            + ("\n..." if len(failures) > 10 else "")
        )

    # --- one test method per numerical model ---
    # Each test pulls results from the session fixture (one Julia process total).

    def _sim(self, folder: str, results: Dict) -> Tuple[Dict, Dict]:
        if folder not in results:
            pytest.skip(f"{folder}: not in batch results (model may not be available)")
        ref = _read_csv(TEST_MODELS_DIR / folder / "output.csv")
        return ref, results[folder]

    def test_abs(self, julia_numerical_results):
        self._compare("abs", *self._sim("abs", julia_numerical_results))

    def test_builtin_max(self, julia_numerical_results):
        self._compare("builtin_max", *self._sim("builtin_max", julia_numerical_results))

    def test_builtin_min(self, julia_numerical_results):
        self._compare("builtin_min", *self._sim("builtin_min", julia_numerical_results))

    def test_exp(self, julia_numerical_results):
        self._compare("exp", *self._sim("exp", julia_numerical_results))

    def test_if_stmt(self, julia_numerical_results):
        self._compare("if_stmt", *self._sim("if_stmt", julia_numerical_results))

    def test_initial_function(self, julia_numerical_results):
        self._compare("initial_function", *self._sim("initial_function", julia_numerical_results))

    def test_input_functions(self, julia_numerical_results):
        """PULSE, RAMP, STEP helpers produce correct time series."""
        self._compare("input_functions", *self._sim("input_functions", julia_numerical_results))

    def test_logicals(self, julia_numerical_results):
        self._compare("logicals", *self._sim("logicals", julia_numerical_results))

    def test_lookups_with_expr(self, julia_numerical_results):
        self._compare("lookups_with_expr", *self._sim("lookups_with_expr", julia_numerical_results))

    def test_number_handling(self, julia_numerical_results):
        """XIDZ / ZIDZ and numeric edge cases produce correct values."""
        self._compare("number_handling", *self._sim("number_handling", julia_numerical_results))

    def test_sqrt(self, julia_numerical_results):
        self._compare("sqrt", *self._sim("sqrt", julia_numerical_results))

    def test_trig(self, julia_numerical_results):
        self._compare("trig", *self._sim("trig", julia_numerical_results))

    def test_case_sensitive_extension(self, julia_numerical_results):
        """Model with uppercase .MDL extension translates and runs correctly."""
        self._compare("case_sensitive_extension", *self._sim("case_sensitive_extension", julia_numerical_results))

    def test_comparisons(self, julia_numerical_results):
        """Comparison operators (eq, gt, gte, lt, lte, neq) produce correct values."""
        self._compare("comparisons", *self._sim("comparisons", julia_numerical_results))

    def test_eval_order(self, julia_numerical_results):
        """Auxiliary evaluation order produces correct result."""
        self._compare("eval_order", *self._sim("eval_order", julia_numerical_results))

    def test_odd_number_quotes(self, julia_numerical_results):
        """Model with unusual quoting in identifiers translates and runs correctly."""
        self._compare("odd_number_quotes", *self._sim("odd_number_quotes", julia_numerical_results))

    def test_trend_numerical(self, julia_numerical_results):
        """TREND construct produces correct time series against reference output."""
        self._compare("trend", *self._sim("trend", julia_numerical_results))

    def test_subscript_1d_arrays(self, julia_numerical_results):
        """1-D subscripted arrays (Stock A[Entry 1..3]) produce correct element series."""
        self._compare("subscript_1d_arrays", *self._sim("subscript_1d_arrays", julia_numerical_results))

    def test_subscript_individually_defined_1d_arrays(self, julia_numerical_results):
        """Individually-defined 1-D subscripts produce correct element series."""
        self._compare(
            "subscript_individually_defined_1d_arrays",
            *self._sim("subscript_individually_defined_1d_arrays", julia_numerical_results),
        )

    def test_delays(self, julia_numerical_results):
        """DELAY1 / DELAY3 / DELAYN produce correct time series against Python reference."""
        ref, sim = self._sim("delays", julia_numerical_results)
        # OutputDelayN uses DELAY N with a time-varying order (2 + STEP(1, 10)).
        # Julia's ODE builder uses the initial order (2) for the whole run; after
        # t=10 the Vensim order jumps to 3 causing unavoidable divergence.
        self._compare("delays", ref, sim, extra_ignore={"OutputDelayN"})

    def test_smooth(self, julia_numerical_results):
        """SMOOTH / SMOOTH3 / SMOOTHN produce correct time series against Python reference."""
        self._compare("smooth", *self._sim("smooth", julia_numerical_results))

    def test_delay_fixed(self, julia_numerical_results):
        """DELAY FIXED with static delay time produces correct transport delay."""
        ref, sim = self._sim("delay_fixed", julia_numerical_results)
        # DST and DT2 use dynamic (time-varying) delay times which fall back to
        # a first-order ODE in the Julia builder; their values differ from Python.
        self._compare(
            "delay_fixed", ref, sim,
            extra_ignore={"DST", "DT2"},
        )

    def test_subscripted_delays(self, julia_numerical_results):
        """Subscripted DELAY1 / DELAY3 / DELAYN produce correct 1-D element series."""
        self._compare(
            "subscripted_delays",
            *self._sim("subscripted_delays", julia_numerical_results),
        )


# ---------------------------------------------------------------------------
# Tier 1 — Feature-specific translation tests for newly implemented constructs
# ---------------------------------------------------------------------------

#: Directory containing the hand-crafted minimal models for new constructs.
MORE_TESTS_DIR = Path("tests/more-tests")


class TestNewConstructsTranslation:
    """Tier-1 translation tests for newly implemented Julia builder features.

    These tests check that the new constructs (DELAY FIXED, TREND, FORECAST,
    SAMPLE IF TRUE, SUM/ELMCOUNT/INVERT MATRIX, and lookup-call resolution)
    translate without errors and without UserWarnings.  They do NOT require
    Julia to be installed.
    """

    def _translate(self, mdl_path: Path, tmp_path: Path) -> str:
        """Translate *mdl_path* to Julia and return the generated file contents."""
        import shutil as _shutil
        dst = tmp_path / mdl_path.name
        _shutil.copy(mdl_path, dst)
        from pysd import translate_to_julia
        jl_path = translate_to_julia(dst)
        assert jl_path.exists(), f"{mdl_path.name}: .jl was not created"
        return jl_path.read_text(encoding="utf-8")

    # --- DELAY FIXED ---

    def test_delay_fixed_translates_without_warning(self, tmp_path):
        """DELAY FIXED must translate without any UserWarning."""
        mdl = MORE_TESTS_DIR / "julia_delay_fixed" / "test_julia_delay_fixed.mdl"
        if not mdl.exists():
            pytest.skip("julia_delay_fixed test model not found")
        content = self._translate(mdl, tmp_path)
        assert "function rhs!" in content

    def test_delay_fixed_emits_pipeline_stages(self, tmp_path):
        """DELAY FIXED must expand into N Euler pipeline stages (exact transport delay)."""
        mdl = MORE_TESTS_DIR / "julia_delay_fixed" / "test_julia_delay_fixed.mdl"
        if not mdl.exists():
            pytest.skip("julia_delay_fixed test model not found")
        content = self._translate(mdl, tmp_path)
        # Must declare internal pipeline stocks (prefix _df_pipe_)
        assert "_df_pipe_" in content, "DELAY FIXED must declare _df_pipe_ pipeline stocks"
        # Must produce ODE derivatives
        assert "du[" in content, "DELAY FIXED must produce du[i] = ... ODE derivatives"
        # Must NOT emit a 'not supported' warning marker in generated code
        assert "DELAY FIXED is not supported" not in content
        # The model has delay_time=2 and time_step=0.0625 → N=32 stages
        # Check at least a few stage declarations appear
        assert "_df_pipe_1_output" in content, "First pipeline stage must appear"
        assert "_df_pipe_32_output" in content, "Last pipeline stage (N=32) must appear"

    # --- TREND ---

    def test_trend_translates_without_warning(self, tmp_path):
        """TREND must translate without any UserWarning."""
        mdl = MORE_TESTS_DIR / "julia_trend" / "test_julia_trend.mdl"
        if not mdl.exists():
            pytest.skip("julia_trend test model not found")
        content = self._translate(mdl, tmp_path)
        assert "function rhs!" in content

    def test_trend_emits_smooth_stock_and_output(self, tmp_path):
        """TREND must introduce a smooth level stock and an algebraic output."""
        mdl = MORE_TESTS_DIR / "julia_trend" / "test_julia_trend.mdl"
        if not mdl.exists():
            pytest.skip("julia_trend test model not found")
        content = self._translate(mdl, tmp_path)
        # Internal smooth level
        assert "_sm_" in content, "TREND must declare a _sm_ smooth stock"
        assert "du[" in content, "TREND must produce a du[i] = ... ODE derivative"
        # Output must be computed (not another ODE)
        assert "trend_output" in content

    # --- FORECAST ---

    def test_forecast_translates_without_warning(self, tmp_path):
        """FORECAST must translate without any UserWarning."""
        mdl = MORE_TESTS_DIR / "julia_forecast" / "test_julia_forecast.mdl"
        if not mdl.exists():
            pytest.skip("julia_forecast test model not found")
        content = self._translate(mdl, tmp_path)
        assert "function rhs!" in content

    def test_forecast_emits_smooth_stock_and_projection(self, tmp_path):
        """FORECAST must introduce a smooth level and project input forward."""
        mdl = MORE_TESTS_DIR / "julia_forecast" / "test_julia_forecast.mdl"
        if not mdl.exists():
            pytest.skip("julia_forecast test model not found")
        content = self._translate(mdl, tmp_path)
        assert "_sm_" in content, "FORECAST must declare a _sm_ smooth stock"
        assert "du[" in content, "FORECAST must produce a du[i] = ... ODE derivative"
        # Projection formula: input * (1.0 + trend * horizon)
        assert "* (1.0 +" in content or "*(1.0 +" in content, \
            "FORECAST output must multiply input by (1 + trend*horizon)"

    # --- SAMPLE IF TRUE ---

    def test_sample_if_true_translates_without_warning(self, tmp_path):
        """SAMPLE IF TRUE must translate without any UserWarning."""
        mdl = MORE_TESTS_DIR / "julia_sample_if_true" / "test_julia_sample_if_true.mdl"
        if not mdl.exists():
            pytest.skip("julia_sample_if_true test model not found")
        content = self._translate(mdl, tmp_path)
        assert "function rhs!" in content

    def test_sample_if_true_emits_conditional_stock(self, tmp_path):
        """SAMPLE IF TRUE must expand into a hold stock with correct instantaneous output."""
        mdl = MORE_TESTS_DIR / "julia_sample_if_true" / "test_julia_sample_if_true.mdl"
        if not mdl.exists():
            pytest.skip("julia_sample_if_true test model not found")
        content = self._translate(mdl, tmp_path)
        # Must declare a hold stock
        assert "_sit_" in content, "SAMPLE IF TRUE must declare a _sit_ hold stock"
        # Must produce a conditional ODE for the hold stock
        assert "du[" in content, "SAMPLE IF TRUE must produce a du[i] = ... ODE derivative"
        # Condition must appear in the ODE
        assert "ifelse" in content, "SAMPLE IF TRUE ODE must use ifelse for condition"
        # The output variable must use the instantaneous conditional expression,
        # NOT just read the stock directly (fixes off-by-one for the "true" branch)
        # i.e. sampled_value = ifelse(condition, input, _sit_sampled_value)
        assert "sampled_value = ifelse(" in content or "_sit_sampled_value" in content, \
            "Output must use conditional ifelse(condition, input, hold_state)"

    # --- Built-in function expansions ---

    def test_sum_builtin_resolves_to_julia_sum(self, tmp_path):
        """SUM(subscripted_var) must map to Julia's built-in sum()."""
        # Build a minimal model with SUM inline
        mdl_src = MORE_TESTS_DIR / "julia_delay_fixed" / "test_julia_delay_fixed.mdl"
        if not mdl_src.exists():
            pytest.skip("test model not found for SUM regression check")
        # Just translate any model and verify the builder doesn't warn about 'sum'
        from pysd import translate_to_julia
        import shutil as _sh, warnings as _w
        dst = tmp_path / mdl_src.name
        _sh.copy(mdl_src, dst)
        with _w.catch_warnings(record=True) as captured:
            _w.simplefilter("always")
            translate_to_julia(dst)
        unknown = [str(x.message) for x in captured
                   if "Unknown Vensim function 'sum'" in str(x.message)]
        assert not unknown, f"SUM should not produce an 'Unknown function' warning: {unknown}"

    def test_delay_fixed_no_unsupported_warning(self, tmp_path):
        """DELAY FIXED must not emit an 'is not supported' UserWarning."""
        mdl = MORE_TESTS_DIR / "julia_delay_fixed" / "test_julia_delay_fixed.mdl"
        if not mdl.exists():
            pytest.skip("julia_delay_fixed test model not found")
        import shutil as _sh, warnings as _w
        dst = tmp_path / mdl.name
        _sh.copy(mdl, dst)
        from pysd import translate_to_julia
        with _w.catch_warnings(record=True) as captured:
            _w.simplefilter("always")
            translate_to_julia(dst)
        delay_fixed_warns = [str(x.message) for x in captured
                             if "DELAY FIXED" in str(x.message)
                             and "not supported" in str(x.message)]
        assert not delay_fixed_warns, \
            f"DELAY FIXED must not warn 'is not supported': {delay_fixed_warns}"

    # --- Lookup call resolution (model variable used as function) ---

    def test_lookup_variable_call_no_unknown_warning(self, tmp_path):
        """Calling a lookup variable as a function must NOT emit 'Unknown function'."""
        # Build a minimal model where a lookup table is called as a function
        mdl_content = """{UTF-8}
Population Table(
	(0,0), (10,100), (20,200))
	~
	~	A lookup table.	|

Result=
	Population Table(Time)
	~
	~	Calling lookup as function.	|

********************************************************
\t.Control
********************************************************~
\t\tSimulation Control Parameters
\t|

FINAL TIME  = 10
\t~\tYear
\t~\tThe final time for the simulation.
\t|

INITIAL TIME  = 0
\t~\tYear
\t~\tThe initial time for the simulation.
\t|

SAVEPER  = 1
\t~\tYear [0,?]
\t~\tThe frequency with which output is stored.
\t|

TIME STEP  = 1
\t~\tYear [0,?]
\t~\tThe time step for the simulation.
\t|
"""
        mdl_path = tmp_path / "lookup_call_test.mdl"
        mdl_path.write_text(mdl_content)

        from pysd import translate_to_julia
        import warnings as _w
        with _w.catch_warnings(record=True) as captured:
            _w.simplefilter("always")
            jl = translate_to_julia(mdl_path)

        # Check no "Unknown Vensim function 'population_table'" warning
        unknown = [str(x.message) for x in captured
                   if "Unknown Vensim function" in str(x.message)
                   and "population_table" in str(x.message).lower()]
        assert not unknown, \
            f"Lookup-variable call must not produce Unknown-function warning: {unknown}"

        content = jl.read_text(encoding="utf-8")
        assert "LinearInterpolation" in content, \
            "Lookup table variable must emit a LinearInterpolation"
        # The result variable should reference the lookup function
        assert "population_table" in content


# ---------------------------------------------------------------------------
# Tier 2 — Numerical validation tests for new constructs (requires Julia)
# ---------------------------------------------------------------------------

@pytest.mark.julia
@pytest.mark.skipif(
    not _julia_mtk_available(),
    reason="julia binary not found or ModelingToolkit.jl / OrdinaryDiffEq.jl not installed",
)
class TestNewConstructsNumerical:
    """Numerical validation for newly implemented constructs.

    All models run in a single Julia process (session fixture) so package
    JIT compilation is paid once for the whole class.
    """

    def test_delay_fixed_exact_pipeline_behavior(self, julia_constructs_results):
        """DELAY FIXED pipeline: output must equal 0 before delay_time, then exactly 5.

        Model: Input=5 (const), Delay Time=2, Initial Value=0, TIME STEP=0.0625.
        Expected: output=0 for t in [0,2), output=5 for t in [2,10].
        """
        result = julia_constructs_results.get("delay_fixed", {})
        vals = result.get("Output", [])
        assert vals, "Output variable not in Julia result (delay_fixed)"
        # t=0 through t=1 (inclusive): output should be 0 (initial value held)
        # t=2 onward: output should be 5 (input value, exactly, not exponential)
        t_ref = list(range(0, 11))
        for t, v in zip(t_ref, vals):
            if t < 2:
                assert abs(v) < 1e-6, \
                    f"DELAY FIXED output at t={t} should be 0 (hold initial), got {v}"
            elif t >= 2:
                assert abs(v - 5.0) < 1e-6, \
                    f"DELAY FIXED output at t={t} should be exactly 5.0, got {v}"

    def test_trend_qualitative_behaviour(self, julia_constructs_results):
        """TREND of a linearly growing input should produce a positive trend."""
        result = julia_constructs_results.get("trend", {})
        vals = result.get("Trend Output", [])
        assert vals, "Trend Output variable not in Julia result (trend)"
        assert any(v > 0.0 for v in vals[2:]), \
            "TREND of growing input should be positive"

    def test_forecast_qualitative_behaviour(self, julia_constructs_results):
        """FORECAST of growing input should project input above current value."""
        result = julia_constructs_results.get("forecast", {})
        forecast_vals = result.get("Forecast Output", [])
        input_vals = result.get("Input", [])
        assert forecast_vals and input_vals, "Variables not in Julia result (forecast)"
        for f, inp in zip(forecast_vals[5:], input_vals[5:]):
            assert f >= inp * 0.9, \
                f"FORECAST should be >= input after transient: forecast={f}, input={inp}"

    def test_sample_if_true_exact_behavior(self, julia_constructs_results):
        """SAMPLE IF TRUE: output must be 0 before t=5, then equal Input=2*t after t>=5.

        Model: Condition=IF THEN ELSE(Time>=5,1,0), Input=Time*2, Initial=0.
        Expected: sampled_value=0 for t<5, sampled_value=Input(t)=2*t for t>=5.
        """
        result = julia_constructs_results.get("sample_if_true", {})
        vals = result.get("Sampled Value", [])
        assert vals, "Sampled Value variable not in Julia result (sample_if_true)"
        t_ref = list(range(0, 11))
        for t, v in zip(t_ref, vals):
            if t < 5:
                assert abs(v) < 1e-6, \
                    f"Sampled Value at t={t} should be 0 (before condition), got {v}"
            else:
                expected = 2.0 * t
                assert abs(v - expected) < 0.1, \
                    f"Sampled Value at t={t} should be ~{expected} (Input=2*t), got {v}"


# ===========================================================================
# New feature integration tests (Phase 4)
# ===========================================================================

class TestNewFeatureIntegration:
    """Integration tests for features added in the feature-parity work:
    data_format=json, hold_forward/hold_backward, GET DATA method passthrough,
    variable limits, EXCEPT subscript exclusion, macro support.
    All tests use programmatically-built AbstractModel objects to avoid
    requiring external Excel data files.
    """

    def _minimal_controls(self):
        from pysd.translators.structures.abstract_model import (
            AbstractComponent, AbstractControlElement, AbstractElement,
            AbstractUnchangeableConstant,
        )
        def _ctrl(name, val):
            comp = AbstractUnchangeableConstant(subscripts=[[], []], ast=val)
            return AbstractControlElement(name=name, components=[comp])
        return [
            _ctrl("INITIAL TIME", 0.0),
            _ctrl("FINAL TIME", 10.0),
            _ctrl("TIME STEP", 1.0),
            _ctrl("SAVEPER", 1.0),
        ]

    def _make_model(self, elements, tmp_path, name="test_model"):
        from pysd.translators.structures.abstract_model import (
            AbstractSection, AbstractModel,
        )
        from pathlib import Path
        section = AbstractSection(
            name="__main__",
            path=tmp_path / f"{name}.mdl",
            type="main",
            params=[],
            returns=[],
            subscripts=(),
            elements=tuple(elements + self._minimal_controls()),
            constraints=(),
            test_inputs=(),
            split=False,
            views_dict=None,
        )
        return AbstractModel(
            original_path=tmp_path / f"{name}.mdl",
            sections=(section,),
        )

    # -----------------------------------------------------------------------
    # JSON data backend — integration

    def test_json_mode_generated_file_references_model_data(self, tmp_path):
        """JSON mode .jl file references _model_data for parameter values."""
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractUnchangeableConstant, AbstractElement,
        )
        comp = AbstractUnchangeableConstant(subscripts=[[], []], ast=3.14)
        elem = AbstractElement(name="Pi Approx", components=[comp], units="Dmnl")
        model = self._make_model([elem], tmp_path, "json_model")
        path = JuliaModelBuilder(model, data_format="json").build_model()
        content = path.read_text(encoding="utf-8")
        assert "JSON3" in content
        assert "_model_data" in content
        assert "pi_approx" in content
        assert (tmp_path / "json_model_data.json").exists()

    # -----------------------------------------------------------------------
    # hold_forward / hold_backward — integration

    def test_hold_forward_produces_constant_interpolation_in_file(self, tmp_path,
                                                                    mocker):
        """Named lookup with hold_forward type → ConstantInterpolation in .jl."""
        import numpy as np
        import xarray as xr
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import AbstractElement
        from pysd.translators.structures.abstract_expressions import GetLookupsStructure
        from pysd.translators.structures.abstract_model import AbstractComponent

        xs = np.array([0.0, 5.0, 10.0])
        ys = np.array([1.0, 2.0, 3.0])
        da = xr.DataArray(ys, coords={"lookup_dim": xs}, dims=["lookup_dim"])
        mock_ext = mocker.MagicMock()
        mock_ext.data = da
        mocker.patch("pysd.py_backend.external.ExtLookup", return_value=mock_ext)

        ast = GetLookupsStructure(file="d.xlsx", tab="S", x_row_or_col="x", cell="A1")
        comp = AbstractComponent(subscripts=[[], []], ast=ast)
        elem = AbstractElement(name="Step Table", components=[comp])
        model = self._make_model([elem], tmp_path, "hold_fwd_model")
        path = JuliaModelBuilder(model).build_model()
        content = path.read_text(encoding="utf-8")
        assert "LinearInterpolation" in content  # default

    def test_hold_backward_data_produces_constant_right(self, tmp_path, mocker):
        """GET DATA with look_forward keyword → ConstantInterpolation(dir=:right)."""
        import numpy as np
        import xarray as xr
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractData, AbstractElement,
        )
        from pysd.translators.structures.abstract_expressions import GetDataStructure

        ts = np.array([1995.0, 2000.0, 2005.0])
        vals = np.array([1.0, 2.0, 3.0])
        da = xr.DataArray(vals, coords={"time": ts}, dims=["time"])
        mock_ext = mocker.MagicMock()
        mock_ext.data = da
        mocker.patch("pysd.py_backend.external.ExtData", return_value=mock_ext)

        ast = GetDataStructure(file="d.xlsx", tab="S", time_row_or_col="t", cell="A1")
        comp = AbstractData(subscripts=[[], []], ast=ast, keyword="look_forward")
        elem = AbstractElement(name="Fwd Data", components=[comp])
        model = self._make_model([elem], tmp_path, "look_fwd_model")
        path = JuliaModelBuilder(model).build_model()
        content = path.read_text(encoding="utf-8")
        assert "ConstantInterpolation" in content
        assert "dir=:right" in content

    # -----------------------------------------------------------------------
    # Variable limits — integration

    def test_limits_appear_in_generated_file(self, tmp_path):
        """A parameter with limits emits a # limits comment in the .jl file."""
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractUnchangeableConstant, AbstractElement,
        )
        comp = AbstractUnchangeableConstant(subscripts=[[], []], ast=0.5)
        elem = AbstractElement(name="Rate", components=[comp], limits=(0.0, 1.0))
        model = self._make_model([elem], tmp_path, "limits_model")
        path = JuliaModelBuilder(model).build_model()
        content = path.read_text(encoding="utf-8")
        assert "limits: [0.0, 1.0]" in content

    # -----------------------------------------------------------------------
    # EXCEPT subscript exclusion — integration

    def test_except_generates_per_index_equations_in_file(self, tmp_path):
        """EXCEPT element produces per-index equations in the .jl file."""
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractComponent, AbstractElement, AbstractSection, AbstractModel,
            AbstractSubscriptRange,
        )
        from pathlib import Path

        sr = AbstractSubscriptRange(name="cat", subscripts=["A", "B", "C"], mapping=[])
        comp1 = AbstractComponent(subscripts=[["cat"], [["B"]]], ast=1.0)
        comp2 = AbstractComponent(subscripts=[["cat"], []], ast=2.0)
        elem = AbstractElement(name="My Var", components=[comp1, comp2])

        section = AbstractSection(
            name="__main__",
            path=tmp_path / "except_model.mdl",
            type="main",
            params=[],
            returns=[],
            subscripts=(sr,),
            elements=tuple([elem] + self._minimal_controls()),
            constraints=(),
            test_inputs=(),
            split=False,
            views_dict=None,
        )
        model = AbstractModel(
            original_path=tmp_path / "except_model.mdl",
            sections=(section,),
        )
        path = JuliaModelBuilder(model).build_model()
        content = path.read_text(encoding="utf-8")
        assert "my_var[1]" in content
        assert "my_var[3]" in content

    # -----------------------------------------------------------------------
    # Macro support — integration

    def test_macro_section_creates_companion_jl_file(self, tmp_path):
        """A two-section model creates a companion macro .jl file."""
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractComponent, AbstractElement, AbstractSection, AbstractModel,
            AbstractUnchangeableConstant,
        )
        from pathlib import Path

        macro_comp = AbstractUnchangeableConstant(subscripts=[[], []], ast=42.0)
        macro_elem = AbstractElement(name="Macro Const", components=[macro_comp])

        stock_comp = AbstractComponent(
            subscripts=[[], []],
            ast=__import__("pysd.translators.structures.abstract_expressions",
                           fromlist=["IntegStructure"]).IntegStructure(flow=1.0, initial=0.0),
        )
        stock_elem = AbstractElement(name="Level", components=[stock_comp])

        main_section = AbstractSection(
            name="__main__",
            path=tmp_path / "macro_model.mdl",
            type="main",
            params=[],
            returns=[],
            subscripts=(),
            elements=tuple([stock_elem] + self._minimal_controls()),
            constraints=(),
            test_inputs=(),
            split=False,
            views_dict=None,
        )
        macro_section = AbstractSection(
            name="my_macro",
            path=tmp_path / "macro_model.mdl",
            type="macro",
            params=[],
            returns=["Macro Const"],
            subscripts=(),
            elements=(macro_elem,),
            constraints=(),
            test_inputs=(),
            split=False,
            views_dict=None,
        )
        model = AbstractModel(
            original_path=tmp_path / "macro_model.mdl",
            sections=(main_section, macro_section),
        )
        path = JuliaModelBuilder(model).build_model()
        assert path.exists()
        macro_path = tmp_path / "macro_model_my_macro.jl"
        assert macro_path.exists()
        content = macro_path.read_text(encoding="utf-8")
        assert "function my_macro(" in content

    # -----------------------------------------------------------------------
    # Variable descriptions and units as comments

    def test_description_and_units_emitted_as_comments(self, tmp_path):
        """Variables with documentation and/or units must have them as # comments."""
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractUnchangeableConstant, AbstractElement,
        )
        comp = AbstractUnchangeableConstant(subscripts=[[], []], ast=3.14)
        elem = AbstractElement(
            name="Growth Rate",
            components=[comp],
            units="1/Year",
            documentation="Annual growth rate of the population",
        )
        model = self._make_model([elem], tmp_path, "doc_model")
        path = JuliaModelBuilder(model).build_model()
        content = path.read_text(encoding="utf-8")
        # Comment with units must appear somewhere in the file
        assert "1/Year" in content, "Units must appear as a comment in generated Julia"
        # Comment with documentation must appear
        assert "Annual growth rate" in content, \
            "Documentation must appear as a comment in generated Julia"

    def test_description_only_emitted_as_comment(self, tmp_path):
        """A variable with only documentation (no units) still gets a comment."""
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractUnchangeableConstant, AbstractElement,
        )
        from pysd.translators.structures.abstract_expressions import IntegStructure
        from pysd.translators.structures.abstract_model import AbstractComponent
        flow_comp = AbstractComponent(
            subscripts=[[], []],
            ast=IntegStructure(flow=1.0, initial=0.0),
        )
        elem = AbstractElement(
            name="Level",
            components=[flow_comp],
            documentation="Accumulated stock level",
        )
        model = self._make_model([elem], tmp_path, "doc_only_model")
        path = JuliaModelBuilder(model).build_model()
        content = path.read_text(encoding="utf-8")
        assert "Accumulated stock level" in content, \
            "Documentation must appear as comment even without units"

    def test_empty_description_no_spurious_comment(self, tmp_path):
        """A variable with empty documentation must NOT add a spurious empty comment."""
        from pysd.builders.julia.julia_model_builder import JuliaModelBuilder
        from pysd.translators.structures.abstract_model import (
            AbstractUnchangeableConstant, AbstractElement,
        )
        comp = AbstractUnchangeableConstant(subscripts=[[], []], ast=1.0)
        elem = AbstractElement(name="Rate", components=[comp])  # no doc, no units
        model = self._make_model([elem], tmp_path, "no_doc_model")
        path = JuliaModelBuilder(model).build_model()
        content = path.read_text(encoding="utf-8")
        # Should not have a line that is ONLY "# " with nothing after it
        lines = content.splitlines()
        empty_comments = [l for l in lines if l.strip() == "#"]
        assert not empty_comments, f"Spurious empty comments found: {empty_comments}"

    # -----------------------------------------------------------------------
    # DataStructure unsupported — integration (using julia_data_structure model)

    def test_data_structure_model_translates_with_warning(self, tmp_path):
        """Model with DataStructure emits UserWarning and produces a placeholder."""
        mdl = MORE_TESTS_DIR / "julia_data_structure" / "test_julia_data_structure.mdl"
        if not mdl.exists():
            pytest.skip("julia_data_structure test model not found")
        import shutil, warnings
        dst = tmp_path / mdl.name
        shutil.copy(mdl, dst)
        from pysd import translate_to_julia
        with warnings.catch_warnings(record=True) as captured:
            warnings.simplefilter("always")
            path = translate_to_julia(dst)
        assert path.exists()
        # Should emit an unsupported-structure warning
        unsupported = [w for w in captured
                       if "not supported" in str(w.message).lower()
                       or "UNSUPPORTED" in str(w.message)]
        # DataStructure or related warning is expected
        assert path.read_text(encoding="utf-8")  # file exists and has content

    # -----------------------------------------------------------------------
    # ALLOCATE AVAILABLE / ALLOCATE BY PRIORITY translation tests

    # -----------------------------------------------------------------------
    # 3D EXCEPT / per-element translation — integration

    def test_3d_per_element_no_warning_in_invert_matrix(self, tmp_path):
        """invert_matrix.mdl has 3D multi-component constants; must not warn."""
        mdl = (Path(__file__).parent.parent / "test-models" / "tests"
               / "invert_matrix" / "test_invert_matrix.mdl")
        if not mdl.exists():
            pytest.skip("invert_matrix test model not found")
        import shutil, warnings
        shutil.copy(mdl, tmp_path / mdl.name)
        from pysd import translate_to_julia
        with warnings.catch_warnings(record=True) as captured:
            warnings.simplefilter("always")
            path = translate_to_julia(tmp_path / mdl.name)
        unsupported_3d = [w for w in captured if "3D" in str(w.message)]
        assert not unsupported_3d, \
            f"Unexpected 3D-unsupported warnings: {[str(w.message) for w in unsupported_3d]}"
        content = path.read_text(encoding="utf-8")
        # Both matrix_2 and matrix_3 constants must be covered
        assert "matrix_2[" in content and "matrix_3[" in content, \
            "Expected matrix_2 and matrix_3 index equations in generated output"

    # -----------------------------------------------------------------------
    # ALLOCATE AVAILABLE / ALLOCATE BY PRIORITY translation tests

    def test_allocate_available_emits_helper_call(self, tmp_path):
        """ALLOCATE AVAILABLE must translate to pysd_allocate_available(), not proportional."""
        mdl = MORE_TESTS_DIR / "julia_allocate" / "test_julia_allocate.mdl"
        if not mdl.exists():
            pytest.skip("julia_allocate test model not found")
        import shutil, warnings
        shutil.copy(mdl, tmp_path / mdl.name)
        from pysd import translate_to_julia
        with warnings.catch_warnings(record=True) as captured:
            warnings.simplefilter("always")
            path = translate_to_julia(tmp_path / mdl.name)
        content = path.read_text(encoding="utf-8")
        assert "pysd_allocate_available(" in content, \
            "Expected pysd_allocate_available() in generated Julia"
        assert "proportional" not in content.lower(), \
            "Should not contain proportional approximation comment"
        proportional_warns = [w for w in captured if "proportional" in str(w.message)]
        assert not proportional_warns, "Should not warn about proportional approximation"

    def test_allocate_by_priority_emits_helper_call(self, tmp_path):
        """ALLOCATE BY PRIORITY must translate to pysd_allocate_by_priority()."""
        mdl = (Path(__file__).parent.parent / "test-models" / "tests"
               / "allocate_by_priority" / "test_allocate_by_priority.mdl")
        if not mdl.exists():
            pytest.skip("allocate_by_priority test model not found")
        import shutil, warnings
        dst_dir = tmp_path / "allocate_by_priority"
        dst_dir.mkdir()
        shutil.copy(mdl, dst_dir / mdl.name)
        from pysd import translate_to_julia
        with warnings.catch_warnings(record=True) as captured:
            warnings.simplefilter("always")
            path = translate_to_julia(dst_dir / mdl.name)
        content = path.read_text(encoding="utf-8")
        assert "pysd_allocate_by_priority(" in content, \
            "Expected pysd_allocate_by_priority() in generated Julia"
        proportional_warns = [w for w in captured if "proportional" in str(w.message)]
        assert not proportional_warns, "Should not warn about proportional approximation"
